### ISSUE TITLE
Fix EXP tests

### ISSUE THREAD

**Issue by blegat** [jump-dev/Pavito.jl#24]
The MPB implementation relied on https://github.com/mlubin/ConicNonlinearBridge.jl/ to bridge the exp constraint into nonlinear constraints. We may want to way https://github.com/jump-dev/MathOptInterface.jl/issues/846 and implement an MOI bridge from the exp constraint to a nonlinear one.

**Comment by ccoffrin** [comment]
As a fall back, I presume one can specify the EXP constraint in a non-linear form rather than a conic, correct?

**Comment by blegat** [comment]
Correct, in fact the bridge would reformulate the exp conic constraint into the exact same nlp form.

**Comment by mlubin** [comment]
Why does Pavito accept EXP constraints? It's an MINLP solver, no a MI-conic solver.

**Comment by blegat** [comment]
It got it from free with the Conic to NLP bridge in MPB. Testing with these did not really test any features of Pavito, it was just additional coverage for Pavito and the Conic to NLP bridges.
By the way, the Pavito support for quadratic constraints can be removed once we have a bridge from quadratic constraints to NLP constraints. I added it as a temporary workaround for consistency with MPB where quad constraints were included in the NLP constraints. It also seemed to be an important use case of Pavito so it deserved a temporary workaround.

**Comment by chriscoey** [comment]
@blegat I think I will close this issue if that's OK - our test coverage is pretty good after #25.

Do we have the bridge from quadratic to NLP constraints in MOI? is it time to remove the temporary workaround for quad constraints?

**Comment by odow** [comment]
Closing because Pavito does not support exponential cones.
