### ISSUE TITLE
jump-dev and v0.3.0

### ISSUE THREAD

**Issue by blegat** [jump-dev/Pavito.jl#33]
@mlubin @chriscoey Any objection to move this package to jump-dev and then release v0.3.0 ? I'm bumping the minor version as it drops the MPB version.

**Comment by chriscoey** [comment]
Sounds good, thanks @blegat

**Comment by mlubin** [comment]
No objection.

**Comment by matbesancon** [comment]
@blegat you wanted to release 0.3.0 here?

**Comment by blegat** [comment]
We released v0.3.0 and v0.3.1. It didn't get reflected on this repo as it seems TagBot is not configure correctly
