### ISSUE TITLE
Can Pavito support RSOCP constraints?

### ISSUE THREAD

**Issue by pqrz** [jump-dev/Pavito.jl#38]
Hi Team,

I was trying to run a RSOCP problem with Pavito, but it seems Pavito doesn't support [RSOCP](https://jump.dev/JuMP.jl/stable/reference/constraints/#JuMP.RotatedSecondOrderCone) constraints?

Minimum reproducible example:
```julia
using JuMP, LinearAlgebra, Cbc, Ipopt, Pavito
u0 = [3,5]
m = Model(optimizer_with_attributes(Pavito.Optimizer, "cont_solver"=>Ipopt.Optimizer, "mip_solver"=>Cbc.Optimizer))
@variable(m, x[1:2])
@objective(m, Min, dot(u0,x))
@constraint(m, [1, 5, x[1], x[2]] in RotatedSecondOrderCone())
optimize!(m)
```

If possible, kindly suggest a resolution for same.

**Comment by blegat** [comment]
Can you try adding the [`RSOCtoNonConvexQuadBridge`](https://jump.dev/MathOptInterface.jl/stable/apireference/#MathOptInterface.Bridges.Constraint.RSOCtoNonConvexQuadBridge) bridge:
```julia
add_bridge(model, MOI.Bridges.Constraint.RSOCtoNonConvexQuadBridge)
```

**Comment by pqrz** [comment]
Hi @blegat,

Haha, was expecting this. 
So, I had indeed try adding this, specifically:

After this line: 
[https://github.com/jump-dev/Pavito.jl/blob/1ebd714cae8f0b60f3fdb6a6e7876d654a7770da/src/MOI_wrapper.jl#L127](https://github.com/jump-dev/Pavito.jl/blob/1ebd714cae8f0b60f3fdb6a6e7876d654a7770da/src/MOI_wrapper.jl#L127
)
add this:
```
127    . 
128    MOI.Bridges.add_bridge(optimizer, MOI.Bridges.Constraint.SOCtoNonConvexQuadBridge{Float64})
129    MOI.Bridges.add_bridge(optimizer, MOI.Bridges.Constraint.RSOCtoNonConvexQuadBridge{Float64})
130   . 
```

**Comment by blegat** [comment]
This time, it's Pavito itself that needs the bridges as it only support linear, quadratic and nonlinear constraints, not conic ones.
So `model` is the JuMP model itself in the line of my previous message.

**Comment by pqrz** [comment]
Perfect!
Works successfully now. 

Thanks a lot, you are the best of the best!

**Comment by pqrz** [comment]
Just, for the record, this is the final code:
```julia
using JuMP, LinearAlgebra, Cbc, Ipopt, Pavito, MathOptInterface
MOI = MathOptInterface
u0 = [3,5]
m = Model(optimizer_with_attributes(Pavito.Optimizer, "cont_solver"=>Ipopt.Optimizer, "mip_solver"=>Cbc.Optimizer))
add_bridge(m, MOI.Bridges.Constraint.SOCtoNonConvexQuadBridge)
add_bridge(m, MOI.Bridges.Constraint.RSOCtoNonConvexQuadBridge)
@variable(m, x[1:2], Int)
@objective(m, Min, dot(u0,x))
@constraint(m, [1, 5, x[1], x[2]] in RotatedSecondOrderCone())
optimize!(m)
```
