### ISSUE TITLE
Add support for MOI.SolverVersion

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/Pavito.jl#71]
@odow do you know how to get the version of the active package, so we can return it as a string?

**Comment by odow** [comment]
I never liked this though
https://github.com/jump-dev/JuMP.jl/blob/6bde748268c579a635c81ccd8c0afe50d9cce0b5/docs/make.jl#L451-L452

You could also parse the TOML file

**Comment by chriscoey** [comment]
Hmm there is PkgVersion.jl - see https://github.com/KlausC/PkgVersion.jl/blob/main/src/PkgVersion.jl

**Comment by chriscoey** [comment]
There is https://discourse.julialang.org/t/how-to-find-out-the-version-of-a-package-from-its-module/37755/16?u=chriscoey but it only works on 1.9+

**Comment by chriscoey** [comment]
@odow could we use some combination of 
```
using TOML

const PACKAGE_VERSION = let
    project = TOML.parsefile(joinpath(pkgdir(@__MODULE__), "Project.toml"))
    VersionNumber(project["version"])
end
```
if the julia version < 1.9, and `pkgversion(@__MODULE__)` for 1.9+? These are taken from that discourse link above.

**Comment by chriscoey** [comment]
If the standard procedure is not to support MOI.SolverVersion in cases like this (pure Julia solvers), then it's OK to close this issue without a fix. I can just use `pkgversion` as a fallback in my own code if I can't get MOI.SolverVersion.

**Comment by chriscoey** [comment]
The above worked for my use case so I'll close
